name: pre-commit
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: willisee/pre-commit:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Run pre-commit (Commit Stage)
        run: pre-commit run --all-files --hook-stage commit
      - name: Run pre-commit (Push Stage)
        run: pre-commit run --all-files --hook-stage push
